version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/usr/src/app/src
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - PORT=3001

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'  
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/public/upload:/usr/src/app/public/upload
    depends_on:
      - db
      - db_backup

  db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=password
      - MYSQL_TCP_PORT=3307
      - MYSQL_DATABASE=okoce
    volumes:
      - db_data:/var/lib/mysql

  db_backup:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=password
      - MYSQL_TCP_PORT=3308
      - MYSQL_DATABASE=okoce_backup
    volumes:
      - db_backup_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80' 
    environment:
      - PMA_ARBITRARY=1 
      - PMA_PORT=3307
      - PMA_HOST=db
      - PMA_PASSWORD=password
      - PMA_USER=testuser

networks:
  backend-network:
    driver: bridge

volumes:
  db_data:
  db_backup_data: